//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegionKit.TheMast.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheMast.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des perles de données avec des trous brûlés à travers leurs centres, attachées entre elles avec une sorte&lt;LINE&gt;de fibre végétale torsadée. Je ne peux pas lire les perles, elles sont bien trop abîmées..
        /// </summary>
        internal static string Fre_PearlChain_1 {
            get {
                return ResourceManager.GetString("Fre-PearlChain-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous obtenu cela des farfouilleurs ? Je vous conseillerais de ne pas leur prendre de perles,&lt;LINE&gt;&lt;PLAYERNAME&gt; - ils les apprécient beaucoup et peuvent être dangereux s&apos;ils sont provoqués..
        /// </summary>
        internal static string Fre_PearlChain_2 {
            get {
                return ResourceManager.GetString("Fre-PearlChain-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une perle de données avec un trou brûlé à travers son centre, attachée avec une sorte&lt;LINE&gt;de fibre végétale torsadée. Je ne peux pas lire la perle, elle est bien trop abîmée..
        /// </summary>
        internal static string Fre_SinglePearlChain_1 {
            get {
                return ResourceManager.GetString("Fre-SinglePearlChain-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avez-vous obtenu cela des farfouilleurs ? Je vous conseillerais de ne pas leur prendre de perles,&lt;LINE&gt;&lt;PLAYERNAME&gt; - ils les apprécient beaucoup et peuvent être dangereux s&apos;ils sont provoqués..
        /// </summary>
        internal static string Fre_SinglePearlChain_2 {
            get {
                return ResourceManager.GetString("Fre-SinglePearlChain-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data pearls with holes burned through their centers, tied with some sort&lt;LINE&gt;of twined plant fiber. I can&apos;t read the pearls, they&apos;re far too damaged..
        /// </summary>
        internal static string PearlChain_1 {
            get {
                return ResourceManager.GetString("PearlChain-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you get this from the scavengers? I&apos;d advise that you don&apos;t take pearls from them,&lt;LINE&gt;&lt;PLAYERNAME&gt; - they value them quite highly and can be dangerous if provoked..
        /// </summary>
        internal static string PearlChain_2 {
            get {
                return ResourceManager.GetString("PearlChain-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data pearl with a hole burned through its center, tied with some sort&lt;LINE&gt;of twined plant fiber. I can&apos;t read the pearl, it&apos;s far too damaged..
        /// </summary>
        internal static string SinglePearlChain_1 {
            get {
                return ResourceManager.GetString("SinglePearlChain-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you get this from the scavengers? I&apos;d advise that you don&apos;t take pearls from them,&lt;LINE&gt;&lt;PLAYERNAME&gt; - they value them quite highly and can be dangerous if provoked..
        /// </summary>
        internal static string SinglePearlChain_2 {
            get {
                return ResourceManager.GetString("SinglePearlChain-2", resourceCulture);
            }
        }
    }
}
